<?php

use App\Models\Department;
use App\Models\DepartmentRequest;
use App\Models\Holiday;
use App\Models\Role;
use App\Models\WorkItem;
use App\Services\Scheduling\WorkItemGenerator;
use Illuminate\Support\Carbon;

beforeEach(function () {
    $this->generator = app(WorkItemGenerator::class);
});

test('a daily checklist generates a work item for the target date', function () {
    [$task, $checklist] = makeTaskWithChecklist();
    $tomorrow = now()->addDay();

    $count = $this->generator->generateForDate($tomorrow);

    expect($count)->toBe(1);
    $item = WorkItem::first();
    expect($item->task_checklist_id)->toBe($checklist->id);
    expect($item->operational_date->toDateString())->toBe($tomorrow->toDateString());
    expect($item->execution_status)->toBe(WorkItem::EXECUTION_PENDING);
});

test('generation is idempotent for the same date', function () {
    makeTaskWithChecklist();
    $tomorrow = now()->addDay();

    $this->generator->generateForDate($tomorrow);
    $second = $this->generator->generateForDate($tomorrow);

    expect($second)->toBe(0);
    expect(WorkItem::count())->toBe(1);
});

test('a weekly checklist only generates on its configured weekdays', function () {
    $monday = Carbon::parse('next monday');
    [, $checklist] = makeTaskWithChecklist([
        'schedule_type' => 'weekly',
        'schedule_config' => ['start_time' => '08:00', 'end_time' => '09:00', 'weekdays' => [(int) $monday->dayOfWeek]],
    ]);

    $tuesday = $monday->copy()->addDay();
    expect($this->generator->generateForDate($tuesday))->toBe(0);
    expect($this->generator->generateForDate($monday))->toBe(1);
});

test('a monthly checklist only generates on its configured day of month', function () {
    makeTaskWithChecklist([
        'schedule_type' => 'monthly',
        'schedule_config' => ['start_time' => '08:00', 'end_time' => '09:00', 'day_of_month' => 15],
    ]);

    $notTheDay = Carbon::parse('2026-10-14');
    $theDay = Carbon::parse('2026-10-15');

    expect($this->generator->generateForDate($notTheDay))->toBe(0);
    expect($this->generator->generateForDate($theDay))->toBe(1);
});

test('a one-time checklist only generates within its date range', function () {
    $start = now()->addDays(5)->startOfDay();
    $end = $start->copy()->addDays(2);

    makeTaskWithChecklist([
        'schedule_type' => 'one_time',
        'schedule_config' => [
            'start_time' => '08:00', 'end_time' => '09:00',
            'date' => $start->toDateString(), 'end_date' => $end->toDateString(),
        ],
    ]);

    expect($this->generator->generateForDate($start->copy()->subDay()))->toBe(0);
    expect($this->generator->generateForDate($start))->toBe(1);
    expect($this->generator->generateForDate($start->copy()->addDay()))->toBe(1);
    expect($this->generator->generateForDate($end))->toBe(1);
    expect($this->generator->generateForDate($end->copy()->addDay()))->toBe(0);
});

test('a checklist that does not work on holidays skips generation on a holiday', function () {
    $tomorrow = now()->addDay();
    Holiday::factory()->create(['date' => $tomorrow->toDateString()]);

    makeTaskWithChecklist(['works_on_holidays' => false]);

    expect($this->generator->generateForDate($tomorrow))->toBe(0);
});

test('a checklist that works on holidays still generates on a holiday', function () {
    $tomorrow = now()->addDay();
    Holiday::factory()->create(['date' => $tomorrow->toDateString()]);

    makeTaskWithChecklist(['works_on_holidays' => true]);

    expect($this->generator->generateForDate($tomorrow))->toBe(1);
});

test('generation respects the task date range', function () {
    $farFuture = now()->addDays(90);
    makeTaskWithChecklist([], ['attributes' => ['ends_at' => now()->addDays(10)]]);

    expect($this->generator->generateForDate($farFuture))->toBe(0);
});

test('event-type checklists are never generated by the h-1 batch job', function () {
    makeTaskWithChecklist([
        'schedule_type' => 'event',
        'schedule_config' => ['response_window_hours' => 24],
    ]);

    expect($this->generator->generateForDate(now()->addDay()))->toBe(0);
});

test('a cross-department checklist only generates once its department request is assigned', function () {
    $ownerDepartment = Department::factory()->create();
    $targetDepartment = Department::factory()->create();

    [$task, $checklist] = makeTaskWithChecklist(
        ['target_department_id' => $targetDepartment->id],
        ['department' => $ownerDepartment]
    );

    DepartmentRequest::create([
        'task_id' => $task->id,
        'task_checklist_id' => $checklist->id,
        'owner_department_id' => $ownerDepartment->id,
        'target_department_id' => $targetDepartment->id,
        'status' => DepartmentRequest::STATUS_PENDING,
    ]);

    $tomorrow = now()->addDay();
    expect($this->generator->generateForDate($tomorrow))->toBe(0);
});

test('a cross-department checklist generates with the assigned pic once accepted', function () {
    $ownerDepartment = Department::factory()->create();
    $targetDepartment = Department::factory()->create();
    $pic = makeUserWithRoles([Role::PIC]);

    [$task, $checklist] = makeTaskWithChecklist(
        ['target_department_id' => $targetDepartment->id],
        ['department' => $ownerDepartment]
    );

    DepartmentRequest::create([
        'task_id' => $task->id,
        'task_checklist_id' => $checklist->id,
        'owner_department_id' => $ownerDepartment->id,
        'target_department_id' => $targetDepartment->id,
        'status' => DepartmentRequest::STATUS_ASSIGNED,
        'assigned_pic_id' => $pic->id,
    ]);

    $tomorrow = now()->addDay();
    expect($this->generator->generateForDate($tomorrow))->toBe(1);
    expect(WorkItem::first()->assignee_id)->toBe($pic->id);
});

test('a weekly quota checklist generates target_count slots the day before the period starts', function () {
    $monday = Carbon::parse('next monday');

    makeTaskWithChecklist([
        'schedule_type' => 'weekly_quota',
        'schedule_config' => [
            'start_time' => '08:00', 'end_time' => '09:00',
            'period' => 'week', 'target_count' => 3,
        ],
    ]);

    $sunday = $monday->copy()->subDay();
    expect($this->generator->generateForDate($sunday))->toBe(3);
    expect(WorkItem::count())->toBe(3);

    $items = WorkItem::all();
    expect($items->every(fn ($item) => $item->operational_date === null))->toBeTrue();
    expect($items->every(fn ($item) => $item->period_start->toDateString() === $monday->toDateString()))->toBeTrue();
});

test('a weekly quota checklist does not regenerate slots mid-period', function () {
    $monday = Carbon::parse('next monday');

    makeTaskWithChecklist([
        'schedule_type' => 'weekly_quota',
        'schedule_config' => [
            'start_time' => '08:00', 'end_time' => '09:00',
            'period' => 'week', 'target_count' => 3,
        ],
    ]);

    $this->generator->generateForDate($monday->copy()->subDay());
    $midWeek = $monday->copy()->addDays(2);

    expect($this->generator->generateForDate($midWeek))->toBe(0);
    expect(WorkItem::count())->toBe(3);
});
